version: '3'

services:
  web:
    build: .
    command: gunicorn library_server_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=library_server_db_user
      - POSTGRES_PASSWORD=library_server_db_password
      - POSTGRES_DB=library_server_dev

volumes:
  postgres_data: